### ISSUE TITLE
Error extract-files@9.0.0: The engine "node" is incompatible with this module.

### ISSUE THREAD

**Issue by aguriken** [Borales/actions-yarn#34]
I added [react-collapse](https://github.com/kunukn/react-collapse) in my project.

Test failed during `yarn install` of github actions.

My build & test yml is below 
```push.yml
name: Push CI

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        name: yarn install
        with:
          cmd: install # will run `yarn install` command
...
```

Error logs:
```sh
Run borales/actions-yarn@v2.0.0
/usr/bin/docker run --name d761dc5ffeb8411da4a9f76bc541ba3e_52e4cc --label 442333 --workdir /github/workspace --rm -e INPUT_CMD -e INPUT_AUTH-TOKEN -e INPUT_REGISTRY-URL -e NPM_AUTH_TOKEN -e NPM_REGISTRY_URL -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/alquimista-hp/alquimista-hp":"/github/workspace" 442333:d761dc5ffeb8411da4a9f76bc541ba3e  "install"
yarn install v1.17.3
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
error extract-files@9.0.0: The engine "node" is incompatible with this module. Expected version "^10.17.0 || ^12.0.0 || >= 13.7.0". Got "10.16.3"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by denisdaigle** [comment]
Also running into this same issue. Have you found a workaround?

**Comment by Borales** [comment]
@aguriken try using https://github.com/actions/setup-node with your required node ver

**Comment by ChristianVermeulen** [comment]
@Borales I have implemented the node version, but it seems it is not used at all.. 🤔 
<img width="1034" alt="Screenshot 2021-05-10 at 10 39 55" src="https://user-images.githubusercontent.com/1062751/117631263-567c9b80-b17c-11eb-96b3-bf93714078e7.png">

**Comment by 94rain** [comment]
Same issue for me... I also followed the steps to set up node version to 12 but still getting the error.

**Comment by Borales** [comment]
Please check the latest release, it's resolved
